---
kind: "pipeline"
type: "docker"
name: "default"

steps:
  - name: "Build docker image"
    image: "plugins/docker"
    settings:
      repo: "jkniest/docker-testing-php"
      tags: latest
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - "tag"
