steps:
    build docker image:
      image: "plugins/docker"
      settings:
        repo: "jkniest/docker-testing-php"
        tags: latest
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
      when:
        - event: push

    release docker image:
      image: "plugins/docker"
      settings:
        repo: "jkniest/docker-testing-php"
        auto_tag: true
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
      when:
        - event: tag
